sudo: required
services:
  - docker
addons:
   apt:
     sources:
       - git-core
     packages:
       - git

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - MODIFIED_DOCS=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E 'README.adoc|^docs/.*.adoc$' | wc -l)
  - '[ $(git log --format=%B  $TRAVIS_COMMIT_RANGE | grep -i "\[gen docs\]" | wc -l) -gt 0 ] || [ $MODIFIED_DOCS -ge 1 ] && GENERATE_DOC=0 || GENERATE_DOC=1'
  - 'echo $GENERATE_DOC'
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      git config user.name "${GH_USER}";
      git config user.email "${GH_EMAIL}";
      git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*;
      git fetch --unshallow origin gh-pages;
      git worktree add -b gh-pages gh-pages origin/gh-pages;
      GH_REF=$(git remote get-url origin | awk "{sub(/https:\/\//,\"https://${GH_TOKEN}@\")}; 1" | awk "{sub(/\.git/, \"\")} 1");
      docker pull rochdev/alpine-asciidoctor:mini;
    fi'

before_script:
  - mkdir -p /home/travis/.arquillian/mvn
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz -P /home/travis/.arquillian/resolver/maven/download
  - tar -xf /home/travis/.arquillian/resolver/maven/download/apache-maven-3.3.9-bin.tar.gz -C ~/.arquillian/mvn
  # Cleanup PR doc previews - until we figure out how to have a webhook on closing the PR
  - 'if [ "${BRANCH}" == "master" ]; then
        cd gh-pages;
        UPDATE_GH_PAGES=0;
        for pr in $(ls -1p pr/ >/dev/null 2>&1 | grep "/$" | sed "s/\/$//"); do
            PR_CLOSED=$(curl https://api.github.com/repos/arquillian/smart-testing/pulls/$pr/merge -H "Authorization:token ${GH_TOKEN}" -I -s -o /dev/null -w "%{http_code}");
            if [ "${PR_CLOSED}" == "204" ]; then
                UPDATE_GH_PAGES=1;
                rm -rf pr/${pr};
            fi
        done;

        if [ $UPDATE_GH_PAGES -eq 1 ]; then
            git commit -m"docs: cleans up closed PR doc preview";
            git push --quiet "${GH_REF}" gh-pages > /dev/null 2>&1;
        fi
        cd ..;
      fi
  '


env:
  - TEST_BED_M2_HOME=/home/travis/.arquillian/mvn/apache-maven-3.3.9

script:
  # - ./mvnw clean verify -P travis -DJAVA_OPTS="-XX:-UseLoopPredicate"
  - 'if [ $GENERATE_DOC -eq 0 ]; then
        ./.asciidoctor/generate.sh --keep;
     fi'

after_success:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      cd gh-pages;
      git add .;
      git commit -m"docs: publishes new documentation";
      git push --quiet "${GH_REF}" gh-pages > /dev/null 2>&1;
      if [ ! -z "${TRAVIS_PULL_REQUEST// }" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
          curl https://api.github.com/repos/arquillian/smart-testing/issues/${TRAVIS_PULL_REQUEST}/comments -H "Authorization:token ${GH_TOKEN}" \
              -X POST -d "{ \"body\": \"Documentation ready for preview at http://arquillian.org/smart-testing/pr/${TRAVIS_PULL_REQUEST}\"}"

      fi
    fi'

after_error:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      docker logs adoc-to-html;
    fi'

after_failure:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      docker logs adoc-to-html;
    fi'
