= Smart Testing
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/smart-testing/master/docs
:numbered:
:sectlink:
:sectanchors:
:sectid:
:source-language: java
:source-highlighter: coderay
:sectnums:
:icons: font
:toc: left
:data-uri:
:imagesdir: docs/images

image:https://travis-ci.org/arquillian/smart-testing.svg?branch=master["Build Status", link="https://travis-ci.org/arquillian/smart-testing"]

*We know which tests you want to run.*

We all know that as the project evolves we keep adding more and more tests to ship our products confidently. This however has
an impact on the build time and thus we waste time waiting for the most important question to be answered - "Did I break anything with my changes?".

Let it be your local development or a CI server - what if you could know this as soon as possible?

We created *Smart Testing* to give you the fastest possible feedback loop when it comes to executing your tests.

ifndef::generated-doc[]

[discrete]
### Installation

To quickly start using Smart Testing all you need to do is to execute following snippet:

`curl -sSL https://git.io/v5jy6 | bash`

You can also add these flags:

  * `-l|--latest` latest published artifact in Maven Central (that's the default)
  * `-v|--version=` - specific version to install

For example:

`curl -sSL https://git.io/v5jy6 | bash -s +++--+++ --latest`

IMPORTANT: The script is tested on Linux, but we do provide basic OSX support footnote:[In case no `.mvn/extension.xml` file exists.] with the fully fledged version coming next release.

IMPORTANT: This script requires `xmllint`, so make sure you have it installed.

[discrete]
### Documentation

To read complete documentation head over to http://arquillian.org/smart-testing/

You can also generate it locally. All you need to have in place is https://docs.docker.com/engine/installation/[Docker].
Simply execute

```
$ ./.asciidoctor/generate.sh
```
and you are set. You will find generated documentation in the `gh-pages` folder.

On Linux you can combine it with following command:

```
./.asciidoctor/generate.sh && xdg-open gh-pages/index.html &>/dev/null
```

This will generate the documentation and open it in the browser.

endif::generated-doc[]

ifdef::generated-doc[]

include::{asciidoctor-source}/what-is-this.adoc[]
include::{asciidoctor-source}/installation.adoc[]
include::{asciidoctor-source}/configuration.adoc[]
include::{asciidoctor-source}/configfile.adoc[]
include::{asciidoctor-source}/usage.adoc[]
include::{asciidoctor-source}/registering-strategies.adoc[]
include::{asciidoctor-source}/surefire-providers.adoc[]
include::{asciidoctor-source}/reports.adoc[]
include::{asciidoctor-source}/jenkins.adoc[]
include::{asciidoctor-source}/refcard.adoc[]
include::{asciidoctor-source}/developing.adoc[]

endif::generated-doc[]
