= Smart Testing
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/smart-testing/master/docs
:numbered:
:sectlink:
:sectanchors:
:sectid:
:source-language: java
:source-highlighter: coderay
:sectnums:
:icons: font
:toc: left

image:https://travis-ci.org/arquillian/smart-testing.svg?branch=master["Build Status", link="https://travis-ci.org/arquillian/smart-testing"]

*We know which tests you want to run.*

We all know that as the project evolves we keep adding more and more tests to ship our products confidently. This however has
an impact on the build time and thus we waste time waiting for the most important question to be answered - "Did I break anything with my changes?".

Let it be your local development or a CI server - what if you could know this as soon as possible?

We created *Smart Testing* to give you the fastest possible feedback loop when it comes to executing your tests.

ifndef::generated-doc[]
To read complete documentation head over to http://arquillian.org/smart-testing/

You can also generate it locally. All you need to have in place is [docker](https://docs.docker.com/engine/installation/).
Simply execute `$ ./.asciidoctor/generate.sh` and you are set.

endif::generated-doc[]

ifdef::generated-doc[]

include::{asciidoctor-source}/what-is-this.adoc[]
include::{asciidoctor-source}/installation.adoc[]
include::{asciidoctor-source}/configuration.adoc[]
include::{asciidoctor-source}/usage.adoc[]
include::{asciidoctor-source}/reports.adoc[]
include::{asciidoctor-source}/refcard.adoc[]
include::{asciidoctor-source}/developing.adoc[]

endif::generated-doc[]
