== Configuration File

You can use smart-testing `YAML` file at `${project.dir}/smart-testing.yml` or at `${project.dir}/smart-testing.yaml`.

You can also point to a custom configuration file from a different project by setting the `const:core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java[name="SMART_TESTING_CONFIG"]` property.

Configuration file looks as follows:

[[config-file]]
[source, yaml, indent=0]
----
include::../core/src/test/resources/configuration/smart-testing.yml[]
----
copyToClipboard:config-file[]

<1> Config file's absolute or relative path from where Smart Testing overwrites parameters not defined in current config file.
<2> This defines mode to be used by Smart Testing.
<3> This defines strategies to be used while finding important tests.
<4> This defines plugin to be used for Smart Testing.
<5> This enables debug logs for Smart Testing.
<6> This disables Smart Testing if set to true.
<7> This enables Smart Testing report if set to true.
<8> This sets first commit sha or `HEAD` notation for inspecting changes.
<9> This sets last commit sha or `HEAD` notation for inspecting changes.
<10> This defines if smart testing should auto correct misspelled strategies.
<11> This defines the pair key/value of custom strategies as list.
<12> This defines list of strategy related configurations that you want to apply while applying strategy.
<13> This enables transitivity.
<14> This defines list of packages to be excluded while applying transitivity.
<15> This defines list of packages to be included while applying transitivity.

All parameters in configuration file are optional. If you haven't used any parameter in configuration file, Smart testing will use default value for that parameter.
You can look at <<_reference_card, references>> for default value of parameter.

However you can overwrite all configuration options using system properties supported by Smart Testing.
You can look <<_reference_card, references>> for all supported system properties.

=== How configuration is applying to each module?
Smart Testing is looking in each module's root dir for configuration file. If it didn't find config file there, it'll look recursively for the first config file in
the parent dir containing pom.xml.

=== How Configuration parameters are inherited?
If config file has `inherit` defined with absolute or relative path of config file, then Smart Testing will
lookup for all undefined properties in config file defined using inherit. However it won't lookup for `disable` parameter.

If config file doesn't contain `inherit` parameter. Then Smart Testing won't inherit any configuration properties.

=== Configuration File per Maven Module:
You can define configuration file per maven module. However it's not mandatory to define configuration per each module.

NOTE: Whenever you are using configuration file per maven module, make sure to define strategies in project's
parent configuration file or using system property. If you are running tests against range of commits, you need to define scm properties in project's parent config file or using system property.
It won't work if you define scm properties in any module's config file and not in parent config file.

e.g.
```xml
parent
 - config
   - smart-testing.yml #<!--1-->
   - api
   - impl-base
   - spi
     - smart-testing.yml #<!--2-->
 - container
    - api
    - impl-base
 - smart-testing.yml #<!--3-->
```

<1>
.parent/config/smart-testing.yml
----
inherit: ../smart-testing.yml
strategies: affected
----

<2>
parent/config/spi/smart-testing.yml
----
strategies: affected,new
----

<3>
.parent/smart-testing.yml
----
strategies: new
scm:
  lastChanges: 1
----

Configuration file selection for the above example will be as follows:

* config/api - parent/config/smart-testing.yml
* config/impl-base - parent/config/smart-testing.yml
* config/spi - parent/config/spi/smart-testing.yml
* container/api - parent/smart-testing.yml
* container/impl-base - parent/smart-testing.yml

<1> inside this file we have inherit: ../smart-testing.yml`, so it will take all undefined properties in this file from the one in `parent/smart-testing.yml`.
<3> inside this file we have `strategies: new` & `scm: lastChanges: 1` defined.(You can set it using respective system property also).

=== Configuration File Reference
The `const:core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java[name="SMART_TESTING_YML"]` file is a `YAML` file defining required configuration to configure Smart Testing.

NOTE: You can use either a `.yml` or `.yaml` extension for this file.

[cols="2,6", options="header"]
|===
|Field | Description

a| inherit
a| This is used to define absolute or relative path for configuration file from where you want to overwrite paremeters not defined in current config file.

a| strategies
a| This is used to define required strategies to find important tests. Look at <<_strategies, strategies>> for all supported options.

a| mode
a| This is used to select mode for Smart Testing. Look at <<_modes, modes>> for all supported options & default value.

a| applyTo
a| This applies smart testing to use with `surefire` or `failsafe` plugin definition.

a| debug
a| This option runs smart testing in debug mode.

a| disable
a| This disables smart testing extension without removing it.

a| report
a| This configures report options for smart testing. Look at <<_report_options, Report Options>> for all available options.

a| scm
a| To run Smart Testing with `SCM` configuration. You can either define `range` or `lastChanges`. Look at <<_scm_options, Scm Options>>
   for all available options.

a| autocorrect
a| This configures Smart Testing to auto correct misspelled strategies to the closest one. For example in case of user set strategies to `nwe`, if `autocorrect` is enabled then it is automatically changed to `new`.

a| customStrategies
a| A list of custom strategies in the form of key/value. It is important to notice that the _key_ part must be prefixed with `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_CUSTOM_STRATEGIES"].`.

a| strategiesConfiguration
a| A list of strategies with it's configuration.
|===

==== Report Options
[cols="2,6", options="header"]
|===
|Field | Description
a| enable
a| This generates smart testing report with selected tests.
|===

==== Scm Options
[cols="2,6", options="header"]
|===
|Field | Description
a| range
a| This configures range for Scm configuration. Look at <<_range_options, Range Options>> for all available options.

a| lastChanges
a| This is used to set the number of commits from `HEAD` that you want to inspect.
|===

==== Range Options
[cols="2,6", options="header"]
|===
|Field | Description
a| head
a| Sets first commit sha or `HEAD` notation.

a| tail
a| Sets last  sha or `HEAD` notation.
|===

==== Affected Configuration Options
[cols="2,6", options="header"]
|===
|Field | Description
a| transitivity
a| Sets transitivity to find all affected tests.

a| exclusions
a| Sets list of packages to be excluded while applying transitivity.

a| inclusions
a| Sets list of packages to be included while applying transitivity.
|===
