== Installation

=== Don't make me think

Ok, just execute following snippet and you are all set:

[[installing-release]]
`curl -sSL https://git.io/v5jy6 | bash` copyToClipboard:installing-release[]

You can also add these flags:

  * `-l|--latest` latest published artifact in Maven Central (that's the default)
  * `-v|--version=` - specific version to install

For example:

[[installing-latest]]
`curl -sSL https://git.io/v5jy6 | bash -s +++--+++ --latest` copyToClipboard:installing-latest[]

This script will automatically do what we described below. If you are curious keep on reading, but you may skip it too.

IMPORTANT: This script requires `xmllint`, and `xsltproc`, so make sure you have it installed.

=== Maven Extension

*Smart Testing* is a Maven extension, so depending on the version of Maven you have to follow slightly different approach of installing it.

==== Maven above 3.1.X

Get Smart Testing Extension _shaded jar_ from http://central.maven.org/maven2/org/arquillian/smart/testing/maven-lifecycle-extension/[Maven Central] and copy it to `M2_HOME/lib/ext`.

==== Maven above 3.3.X

You can still use the process described at <<Maven >= 3.1.X>> or use the new _core extension configuration mechanism_ by
creating folder called `.mvn` in the root of your project and create inside it an `extensions.xml` file
which registers the smart testing extension:

[[smart-testing-extension]]
[source, xml,indent=0]
.${maven.projectBasedir}/.mvn/extensions.xml
----
include::../functional-tests/test-bed/src/main/resources/extensions.xml[]
----
copyToClipboard:smart-testing-extension[]

++++
<script type="text/javascript" src="https://asciinema.org/a/131840.js" id="asciicast-131840" async></script>
++++
