== Reference Card

=== Installation

[[extension]]
[source, xml,indent=0]
.${maven.projectBasedir}/.mvn/extensions.xml
----
include::../functional-tests/test-bed/src/main/resources/extensions.xml[]
----
copyToClipboard:extension[]

=== Configuration

[cols="1,2,2,1", options="header"]
|===
|Property | Description |  Default | Possible Values

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_MODE"]`
|Set running mode
a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="DEFAULT_MODE"]`
a|`ordering`, `selecting`

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING"]`
|Set strategies in CSV
| -
a|`new`, `changed`, `affected`, `failed`, `categorized`

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_DISABLE"]`
|Disable Smart Testing
a|`false`
a|`true`, `false`

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_APPLY_TO"]`
|Set plugin to apply Smart Testing in CSV
a|`surefire, failsafe`
a|`surefire`, `failsafe`

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_AUTOCORRECT"]`
|Enable auto correct of misspelled strategies
a|`false`
a|`true`, `false`

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java[name="SMART_TESTING_CONFIG"]`
|Set custom configuration file
a| -
a|custom configuration `yml` file
|===

=== Strategies

[cols="2,2,1,1", options="header"]
|===
|Property | Description | Default | Applicable Strategies

a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="SCM_RANGE_TAIL"]`
|Set first commit id for inspecting changes
a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="HEAD"]~const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="DEFAULT_LAST_COMMITS"]`
a|`new`, `changed`, `affected`

a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="SCM_RANGE_HEAD"]`
|Set last commit id for inspecting changes
a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="HEAD"]`
a|`new`, `changed`, `affected`

a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="SCM_LAST_CHANGES"]`
|Set the number of commits from `HEAD` that you want to inspect
a|`const:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="DEFAULT_LAST_COMMITS"]`
a|`new`, `changed`, `affected`

a|`const:strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedConfiguration.java[name="SMART_TESTING_AFFECTED_INCLUSIONS"]`
|Set classes to be included for scanning
a|
a|`affected`

a|`const:strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedConfiguration.java[name="SMART_TESTING_AFFECTED_EXCLUSIONS"]`
|Set classes to be excluded for scanning
a|
a|`affected`

a| `const:strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedConfiguration.java[name="SMART_TESTING_AFFECTED_TRANSITIVITY"]`
|Set transitivity enabled
a|const:strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedConfiguration.java[name="DEFAULT_SMART_TESTING_AFFECTED_TRANSITIVITY_VALUE"]
a|`affected`

a| `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_CUSTOM_STRATEGIES"].<strategyName>`
|Register custom strategies implementations
a|
a|Value is the Maven coordinates of the custom strategy

a| `const:strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java[name="SMART_TESTING_CATEGORIZED_CATEGORIES"]`
| List of categories the strategy should be looking for (can be either whole fully qualified names or only simple class names)
a| -
a|`categorized`

a| `const:strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java[name="SMART_TESTING_CATEGORIZED_CASE_SENSITIVE"]`
| Sets case sensitivity of the category names.
a| `false`
a|`categorized`

a| `const:strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java[name="SMART_TESTING_CATEGORIZED_MATCH_ALL"]`
| Sets that the classes should contain all categories specified in the list of the categories.
a| `false`
a|`categorized`

a| `const:strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java[name="SMART_TESTING_CATEGORIZED_REVERSED"]`
| Sets that the selection should be reversed - all classes that don't match the categories will be selected.
a| `false`
a|`categorized`
|===

=== Getting insights of the execution

[cols="1,2,2", options="header"]
|===
|Property | Description | Default

a|`const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_DEBUG"]`
a|enables the debug mode (alternatively you can use Maven debug output `(-X)` flag)
a|`false`

|===

=== Configuration File

[[configuration-file]]
[source, yaml, indent=0]
----
include::../core/src/test/resources/configuration/smart-testing-with-lastChanges.yml[]
----
copyToClipboard:configuration-file[]

