== Registering Custom Strategies

By default *Smart Testing* comes with a set of strategies such as `new`, `changed`, `affected`, `failed` or `categorized`, but you can implement your own strategies and registering them.

To do it you just need to follow next four steps:

* Implement `org.arquillian.smart.testing.spi.TestExecutionPlannerFactory` Java SPI and registering as such.
* Implement `org.arquillian.smart.testing.spi.TestExecutionPlanner` interface.
* Register strategy on Smart Testing configuration file (optional).

=== Implementing TestExecutionPlannerFactory

`TestExecutionPlannerFactory` is a Java SPI interface that manages the creation of the strategy.
You need to implement three simple methods, two related with the name of the strategy and one that generates the strategy class.

As an example from `failed` strategy:

[source, java]
.FailedTestsDetectorFactory.java
----
include::../strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetectorFactory.java[tag=documentation]
----
<1> Returns the alias of the strategy
<2> Returns an instance of `TestExecutionPlanner`

Of course as any other Java SPI, you need to register it in `META-INF/services`.

[source, properties]
.META-INF/services/org.arquillian.smart.testing.spi.TestExecutionPlannerFactory
----
include::../strategies/failed/src/main/resources/META-INF/services/org.arquillian.smart.testing.spi.TestExecutionPlannerFactory[]
----

=== Implementing TestExecutionPlanner

`TestExecutionPlanner` is the implementation of the strategy.
Apart from the method `getName()` that returns a name of the strategy there are two important methods:

[source, java]
----
include::../core/src/main/java/org/arquillian/smart/testing/spi/TestExecutionPlanner.java[tag=documentation]
----

These methods return a collection of the tests that must be executed.
There is only one call of one of these two methods - it won't happen that both methods are called at once. The reason for the existence of these two methods is that in some environments there aren't available `Classes` for the tests, but just the names.

For example, failed strategy is implemented as:

[source, java]
.FailedTestsDetector.java
----
include::../strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetector.java[tag=documentation]
----
<1> Method that returns list of tests to execute based on the provided set of fully qualified class names of tests that were previously selected to be executed.
<2> Method that returns list of tests to execute based on the provided set of tests classes that were previously selected to be executed.
<3> `TestSelection` requires fully qualified test class name and the strategy where is calculated

==== ChangeStorage, ChangeResolver and TestResultParser

*Smart Testing* provides some services to get some common operations.
These services can be used to get information from current project.

===== ChangeStorage

Change Storage service is used to get the changes (from SCM perspective) that has occurred in current project.
This service does not read changes from SCM directly but from a file that has precalculated all changes at the beginning of the Smart Testing process.

Notice that in this way your strategy is more performant since, code does not need to calculate changes for each strategy.

To get it you just need to call `new JavaSPILoader().onlyOne(ChangeStorage.class).get()`.

===== ChangeResolver

Change Resolver service is like <<ChangeStorage>> but in this case the changes are calculated directly from SCM.

To get it you just need to call `new JavaSPILoader().onlyOne(ChangeResolver.class).get()`.

This service is usually not used directly in strategies since we recommend using <<ChangeStorage>> service for this purposes and just fall back to this service in case of error.

For example:

[source, java]
----
include::../strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetector.java[indent=0, tag=read_changes]
----
<1> Changes are read from precalculated file
<2> Fallback to calculate directly from SCM

===== TestResultParser

Test Result Parser is a service that reads previous test results.
Currently it behaves like a parser for `surefire` report file.

To use it you just need to call `new JavaSPILoader().onlyOne(TestResultParser.class).get()`.

=== Registering strategy

Finally you need to register strategy in Smart Testing configuration file where you set the strategy name as key and the Maven coordinates as value.
This file is required so *Smart Testing* can automatically register the artifacts in build tool script.

As an example of registering previous strategy:

[source, yml]
.smart-testing.yml
----
customStrategies:
    - smart.testing.strategy.failed=org.arquillian.smart.testing:strategy-failed:1.0.0
----

It is important to notice that the _key_ part must be prefixed with `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_CUSTOM_STRATEGIES"].`.

If you need to specify any additional coordinate (such as type or classifier), you have to use the whole coordinates format:
`groupId:artifactId:packaging:classifier:version:scope`

=== Alternative Approach

You can still use another approach to register the pair _strategy.name_=_Maven:coordinates_ without configuring them in Smart Testing configuration file and it is using a System property.

For example <<custom-strategy, previous example>> would be equivalent as running *Smart Testing* with next System property:

`-Dsmart.testing.strategy.failed=org.arquillian.smart.testing:strategy-failed:1.0.0`

Notice again that it must be prefixed with `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_CUSTOM_STRATEGIES"].`.




