== Reports

=== Build Artifacts

To identify which tests were selected to run looking in the logs (or even using some CLI tricks with `grep`) is not the
most efficient way to get a quick answer to:

  * How tests are ordered?
  * To which strategy they belong?
  * What was the configuration used?

`Smart Testing` provides concise report in the `XML` format with all this information at hand.

Here’s how the sample report looks like:

[source, xml, indent=0]
----
include::../core/src/test/resources/sample-report.xml[]
----

=== Configuration

By default this feature is disabled. You can enable it by setting property `const:core/src/main/java/org/arquillian/smart/testing/Configuration.java[name="ENABLE_REPORT_PROPERTY"]` to `true`.

You will get generated reports in `target/smart-testing-report.xml` by default.

To change the location of the generated output report, following properties
should be set to the desired alternative location.

`const:core/src/main/java/org/arquillian/smart/testing/Configuration.java[name="SMART_TESTING_REPORT_DIR"]`:: To configure directory where generated reports should be stored.
`const:core/src/main/java/org/arquillian/smart/testing/Configuration.java[name="SMART_TESTING_REPORT_NAME"]`:: To configure the file name of the generated report.

