== Reports

=== Build Artifacts

To identify which tests were selected to run looking in the logs (or even using some CLI tricks with `grep`) is not the
most efficient way to get a quick answer to:

  * How tests are ordered?
  * To which strategy they belong?
  * What was the configuration used?

`Smart Testing` provides concise report in the `XML` format with all this information at hand.

Here’s how the sample report looks like:

[source, xml, indent=0]
----
include::../core/src/test/resources/sample-report.xml[]
----

=== Configuration

By default this feature is disabled. You can enable it by setting property `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_REPORT_ENABLE"]` to `true`.
If you use the property, then you get the generated reports in `target/const:core/src/main/java/org/arquillian/smart/testing/hub/storage/local/AfterExecutionLocalStorage.java[name="SMART_TESTING_TARGET_DIRECTORY_NAME"]/const:core/src/main/java/org/arquillian/smart/testing/hub/storage/local/AfterExecutionLocalStorage.java[name="REPORTING_SUBDIRECTORY"]` for every module separately.

If you are running Smart Testing in debug mode using property `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_DEBUG"]` or Maven build output in debug mode using `-X` or `--debug` then Smart Testing will generate report.

