== Usage

=== Examples

After <<Installation, installing>> *Smart Testing Maven Extension* you can use any goal you use with `maven-surefire-plugin`
or `maven-failsafe-plugin`.

To configure it you only need to pass from CLI the Java system properties.
Let's see some examples:

*You want to run only tests that you've just added or modified locally*

`$ mvn clean test -Dsmart.testing.mode=selecting -Dsmart.testing="new, changed"`

*You want to run all tests but given priority to the latest tests added or modified*

`$ mvn clean test -Dsmart.testing.mode=ordering -Dscm.last.changes=1 -Dsmart.testing="new, changed"`

TIP: `smart.testing.mode` is not mandatory in case of `ordering` because it is the **default** mode.

*You want to run only tests that validates new or modified business classes locally*

`$ mvn clean test -Dsmart.testing.mode=selecting -Dsmart.testing="affected"`

When you are running Smart Testing, you'll see following logs in the console, showing your current configuration:

----
INFO: Smart-Testing - Applied strategies: [new, affected]
INFO: Smart-Testing - Applied usage: [selecting]
----

This can be used as feedback to check that the extension has been installed correctly.

=== Disabling Smart Testing

Sometimes you might want to disable smart testing extension without removing it.

To do it you just need to set `smart.testing.disable` Java system property to `true` and then tests will
run with standard `surefire` / `failsafe` plugins.

=== Plugin Selection

*Smart testing* extension hooks into `surefire` and `failsafe` lifecycle to provide the order/selection of tests to execute.

If you only want to use smart testing on `surefire` or `failsafe` plugin definition.

To do it you just need to set `smart.testing.apply.to` with either `surefire` or `failsafe` to just enable in one of them.

=== Debug Mode

In order to get diagnostic information related to Smart testing extension, you can enable the debug mode by either
setting the system property `smart.testing.debug` or by setting the mvn debug output `(-X)` flag 
along with smart testing.

Debug mode by default writes smart testing debug level logs to the console.

Debug logs retrieves information related to smart testing logged at Debug level, system properties set by the user, 
test selection information and modified pom.xml stored at `target/smart-testing` directory of each 
sub-module as `smart-testing-pom.xml`

=== Specifying Concrete Set of Test Classes

During development, you may want to run a single test class or a set of concrete test classes.
You can do this by setting the maven `test` property to specific test class(es).

==== To Run a Single Test

`$ mvn test -Dtest=SampleTest`

NOTE: This configuration disables smart testing and executes only the specified sample test.

==== To Run Multiple Test Classes

You can also choose to run only a concrete set of multiple test classes.

`$ mvn test -Dtest=SampleOneTest, SampleTwoTest`

NOTE: When multiple specific tests are set without any pattern, smart testing is disabled just like the case 
for single test.

You can further choose to execute multiple test classes in combination with smart testing's <<configuration#_modes, 
`selecting`>> and <<configuration#_modes,`ordering`>> mode by using patterns as 
http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html[supported by Maven].

`$ mvn test -Dtest=Sample*Test`

When used with `ordering` mode, the specified tests are executed in the order defined by the smart testing
strategy used. If none is applicable to the strategy, they are executed in order defined by Surefire.

When used with `selecting` mode, the specified tests that fit the defined strategy are executed.
However, if none fulfil the strategy criteria, no tests would be executed.

=== Skipping Tests

To skip executing the tests for a particular project, Smart Testing aligns with 
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html[Maven Surefire/Failsafe 
plugins' skip test functionality] and respects system properties `skipTests`, `skipITs` and `maven.test.skip`.

=== Running Examples

==== Execute Smart Testing with Changed strategy and Selecting Mode

++++
<script type="text/javascript" src="https://asciinema.org/a/132108.js" id="asciicast-132108" async></script>
++++

==== Execute Smart Testing with Affected strategy and Selecting Mode

++++
<script type="text/javascript" src="https://asciinema.org/a/132434.js" id="asciicast-132434" async></script>
++++
