== Usage

=== Examples

After <<Installation, installing>> *Smart Testing Maven Extension* you can use any goal you use with `maven-surefire-plugin`
or `maven-failsafe-plugin`.

To configure it you only need to pass from CLI the Java system properties.
Let's see some examples:

Remember that the default **mode** is `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="DEFAULT_MODE"]`.

*You want to run only tests that you've just added or modified locally*

[[selectingChanged]]
`mvn clean test -Dconst:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING"]="new, changed"`  copyToClipboard:selectingChanged[]

*You want to run all tests but given priority to the latest tests added or modified*

[[orderingChanged]]
`mvn clean test -Dconst:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_MODE"]=ordering -Dconst:core/src/main/java/org/arquillian/smart/testing/scm/ScmRunnerProperties.java[name="SCM_LAST_CHANGES"]=1 -Dconst:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING"]="new, changed"`  copyToClipboard:orderingChanged[]

*You want to run only tests that validates new or modified business classes locally*

[[selectingAffected]]
`mvn clean test -Dconst:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING"]="affected"`  copyToClipboard:selectingAffected[]

When you are running Smart Testing, you'll see following logs in the console, showing your current configuration:

----
[INFO] [Smart Testing Extension] Applied strategies: [new, affected]
[INFO] [Smart Testing Extension] Applied usage: [selecting]
----

This can be used as feedback to check that the extension has been installed correctly.

=== Disabling Smart Testing

Sometimes you might want to disable smart testing extension without removing it.

To do it you just need to set `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_DISABLE"]` Java system property to `true` and then tests will
run with standard `surefire` / `failsafe` plugins.

=== Plugin Selection

*Smart testing* extension hooks into `surefire` and `failsafe` lifecycle to provide the order/selection of tests to execute.

If you only want to use smart testing on `surefire` or `failsafe` plugin definition.

To do it you just need to set `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_APPLY_TO"]` with either `surefire` or `failsafe` to just enable in one of them.

=== Debug Mode

In order to get diagnostic information related to Smart Testing extension, you can enable the debug mode by either
setting the system property `const:core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java[name="SMART_TESTING_DEBUG"]` or by setting the mvn debug output `(-X)` flag to have the entire build execution
in the debug mode (available out of the box in Maven).

Debug logs provide information related to smart testing execution, system properties set by the user,
test selection information. In addition for each and every module we store modified `pom.xml` at `target/smart-testing/reporting`
as `smart-testing-effective-pom.xml`

NOTE: All Smart Testing related logs can be found with the prefix `Smart Testing Extension -`

=== Specifying Concrete Set of Test Classes

During development, you may want to run a single test class or a set of concrete test classes.
You can do this by setting the maven `test` property to specific test class(es).

==== To Run a Single Test

[[singleTest]]
`mvn test -Dtest=SampleTest`  copyToClipboard:singleTest[]

NOTE: This configuration disables smart testing and executes only the specified sample test.

==== To Run Multiple Test Classes

You can also choose to run only a concrete set of multiple test classes.

[[multipleTests]]
`mvn test -Dtest=SampleOneTest, SampleTwoTest`  copyToClipboard:multipleTests[]

NOTE: When multiple specific tests are set without any pattern, smart testing is disabled just like the case 
for single test.

You can further choose to execute multiple test classes in combination with smart testing's <<_modes,
`selecting`>> and <<_modes,`ordering`>> mode by using patterns 
http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html[supported by Maven].

[[starMultipleTests]]
`mvn test -Dtest=Sample*Test`  copyToClipboard:starMultipleTests[]

When used with `ordering` mode, the specified tests are executed in the order defined by the smart testing
strategy used. If none is applicable to the strategy, they are executed in order defined by Surefire.

When used with `selecting` mode, the specified tests that fit the defined strategy are executed.
However, if none fulfil the strategy criteria, no tests would be executed.

=== Skipping Tests

To skip executing the tests for a particular project, Smart Testing aligns with 
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html[Maven Surefire/Failsafe 
plugins' skip test functionality] and respects system properties `skipTests`, `skipITs` and `maven.test.skip`.

=== Running Examples

==== Execute Smart Testing with Changed strategy and Selecting Mode

++++
<script type="text/javascript" src="https://asciinema.org/a/132108.js" id="asciicast-132108" async></script>
++++

==== Execute Smart Testing with Affected strategy and Selecting Mode

++++
<script type="text/javascript" src="https://asciinema.org/a/132434.js" id="asciicast-132434" async></script>
++++
