== What is this?

*Smart Testing* is a tool that speeds up the test running phase by reordering test execution plan to fail fast execution as soon as possible.

Suppose that you need to implement a new feature in your current project.
If you are following _TDD_ / _BDD_ approach, you'll write some test(s) to validate that the new feature behaves as expected.
Then you'll implement the new feature and when you get that all tests passes, last step is to push this code to your _SCM_ server, which probably will trigger a bew build in your CI server running all the tests.

And at this point it can occurs two things:

. The build takes several minutes and it does not fail.
. The build takes several minutes but it fails because your new tests are failing (yes I know it worked in your machine).

Notice that you have no clue when your new tests are going to be executed.
They could be the first ones, in that case your build will fail fast, or they might be the last ones, so you'll need to wait some time until you get the failure.

*Smart testing* project avoids this uncertainty by ordering tests so that the first tests that could fail (because they are new or because failed previously) are going to executed first.
Thanks of that your build is going to fail fast, which means that for example after a few seconds, you can have some certainty that the build is going to succeed and you can start working on another task.

=== Technical Details

Currently Smart Testing project is implemented as a Maven extension and works together with `maven-surefire-plugin` and `maven-failsafe-plugin`.

In our plan is to extend smart testing to other build tools such as *Gradle*, as well as other languages.

=== Minimum requirements

Smart Testing tool has next requirements:

Java:: Requires Java 8.
Maven:: Tested with _Maven 3.3.9_ and _3.5.0_ but any version above (_Maven 3.1.X_) should work. Our recommendation is that you use at least _3.3.X_ version to avoid any extension API problems.
Surefire/Failsafe:: Minimum version required is _2.19.1_ or above. It is important to make sure that you have defined in your `pom.xml`.
